name: Pritunl Client GitHub Action
description: Establish a Pritunl VPN connection using Pritunl Client supporting OpenVPN (ovpn) and WireGuard (wg) modes on GitHub Actions.

inputs:
  profile-file:
    description: 'The corporate provided or self-obtained Pritunl Profile Key file.'
    required: true
    default: ''

  profile-pin:
    description: 'The Pritunl Profile PIN/Password if provided.'
    required: false
    default: ''

  profile-server:
    description: 'The Pritunl Profile Server if provided, especially multiple servers in a profile.'
    required: false
    default: ''

  vpn-mode:
    description: 'The VPN mode from the two choices is `ovpn` for OpenVPN or `wg` for WireGuard.'
    required: false
    default: 'ovpn'

  client-version:
    description: 'The Version of Pritunl Client to use.'
    required: false
    default: 'from-package-manager'

  start-connection:
    description: 'Start the VPN Connection Automatically.'
    required: false
    default: 'true'

  ready-profile-timeout:
    description: 'Wait for Ready Profile Timeout.'
    required: false
    default: '3'

  established-connection-timeout:
    description: 'Wait for Established Connection Timeout.'
    required: false
    default: '30'

outputs:
  client-id:
    description: "Pritunl Client ID"
    value: ${{ steps.pritunl-client.outputs.client-id }}

runs:
  using: "composite"
  steps:
    - name: Setup Pritunl Client
      id: pritunl-client
      env:
        PRITUNL_PROFILE_FILE: ${{ inputs.profile-file }}
        PRITUNL_PROFILE_PIN: ${{ inputs.profile-pin }}
        PRITUNL_PROFILE_SERVER: ${{ inputs.profile-server }}
        PRITUNL_VPN_MODE: ${{ inputs.vpn-mode }}
        PRITUNL_CLIENT_VERSION: ${{ inputs.client-version }}
        PRITUNL_START_CONNECTION: ${{ inputs.start-connection }}
        PRITUNL_READY_PROFILE_TIMEOUT: ${{ inputs.ready-profile-timeout }}
        PRITUNL_ESTABLISHED_CONNECTION_TIMEOUT: ${{ inputs.established-connection-timeout }}
      shell: bash
      run: |
        # Executing ./pritunl-client.sh
        "$GITHUB_ACTION_PATH$([[ "$RUNNER_OS" == "Windows" ]] && echo '\' || echo '/')pritunl-client.sh"

branding:
  icon: server
  color: gray-dark
