name: Pritunl Client GitHub Action
description: Establish a Pritunl VPN connection using the Pritunl Client that supports OpenVPN and WireGuard modes on GitHub Actions.

inputs:
  profile-file:
    description: 'The corporate provided or self-obtained Pritunl Profile Key file.'
    required: true
    default: ''

  profile-pin:
    description: 'The Pritunl Profile PIN/Password if provided.'
    required: false
    default: ''

  vpn-mode:
    description: 'The VPN mode from the two choices is `ovpn` for OpenVPN or `wg` for WireGuard.'
    required: false
    default: 'ovpn'

  client-version:
    description: 'The Version of Pritunl Client to use.'
    required: false
    default: 'package-manager'

  start-connection:
    description: 'Start the VPN Connection Automatically.'
    required: false
    default: 'true'

outputs:
  client-id:
    description: "Pritunl Client ID"
    value: ${{ steps.pritunl-client.outputs.client-id }}

runs:
  using: "composite"
  steps:
    - name: Pritunl Client GitHub Action
      id: pritunl-client
      env:
        PROFILE_FILE: ${{ inputs.profile-file }}
        PROFILE_PIN: ${{ inputs.profile-pin }}
        VPN_MODE: ${{ inputs.vpn-mode }}
        CLIENT_VERSION: ${{ inputs.client-version }}
        START_CONNECTION: ${{ inputs.start-connection }}
      shell: bash
      run: |
        # Execute `pritunl-client.sh`
        [[ "$RUNNER_OS" == "Windows" ]] && separator="\\" || separator="/"
        bash "$GITHUB_ACTION_PATH${separator}pritunl-client.sh"

branding:
  icon: server
  color: gray-dark
